### ISSUE TITLE
add "show tables"

### ISSUE THREAD

**Issue by ichengchao** [mergestat/mergestat-lite#168]
in mysql, we can use "show tables" ,"desc table_name". 
really looking forward meet this feature

**Comment by ichengchao** [comment]
awesome!
how can i list all tables? (like mysql "show tables")

**Comment by patrickdevivo** [comment]
yep, so just running `askgit "PRAGMA table_info(commits)"` will output the table above 🙂 - you can replace `commits` with any table table name (`askgit "PRAGMA table_info(refs)"` to see the columns for that table.

I will close this issue out when we have the above documented in the README
