### ISSUE TITLE
Link do full installation docs from README.md does not works

### ISSUE THREAD

**Issue by gustawdaniel** [mergestat/mergestat-lite#328]
https://docs.mergestat.com/getting-started-cli/installation

displays page not found

If would be great if you would publish package for `dnf`.

**Comment by patrickdevivo** [comment]
Thanks for bringing this up @gustawdaniel! There was a typo in the redirects we set up for older routes: https://github.com/mergestat/docs/pull/51/files

That's now been fixed. We'll also need to update those links in the README.

I will close this issue and create another for publishing a `dnf` package
